<a href="https://colab.research.google.com/github/slng09/advance-task22/blob/main/cleanfile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd
import numpy as np
import pandas as pd
from scipy import stats
from matplotlib import pyplot as plt
import seaborn as sns

#--- suppress warnings ---
import warnings
warnings.filterwarnings("ignore")

In [112]:
# Read CSV
from google.colab import files
uploaded = files.upload()
import io
df = pd.read_csv(io.BytesIO(uploaded["Tasmania - Metro Hobart _GTFS.txt"]),sep=',')
df.head()

Saving Tasmania - Metro Hobart _GTFS.txt to Tasmania - Metro Hobart _GTFS (1).txt

,stop_id,stop_code,stop_name,stop_desc,stop_lat,stop_lon,zone_id,stop_url,location_type,parent_station
0,434,NaN,45 Stratton Ave,Stratton Ave near Baldwin Pl,-42.859574,147.277761,NaN,NaN,0,NaN
1,512,NaN,** Stop Closed [Acton Cr #37],NaN,-42.827829,147.288276,NaN,NaN,0,NaN
2,513,NaN,** Stop Closed [Acton Cr #38],NaN,-42.826764,147.289645,NaN,NaN,0,NaN
3,3886,NaN,** Stop Deleted,NaN,-42.734262,147.240605,NaN,NaN,0,NaN
4,4143,NaN,** Stop Not In Use,NaN,-42.857649,147.401647,NaN,NaN,0,NaN

In [113]:
df.isnull().sum()

stop_id              0
stop_code         1210
stop_name            0
stop_desc          351
stop_lat             0
stop_lon             0
zone_id           2457
stop_url          2457
location_type        0
parent_station    2430
dtype: int64

In [99]:
def clean_column_name(column_names):
    clean_column_names = []
    for c in column_names:
        c = c.lower().replace(' ','_')
        clean_column_names.append(c)
    return clean_column_names    

df.columns = clean_column_name(df.columns)

In [100]:
df.columns

Index(['postcode', 'suburb', 'state', 'city', 'statecode', '1_br_flat',
       '2_br_flat', '3_br_flat', '4_br_flat', '1_br_house', '2_br_house',
       '3_br_house', '4_br_house'],
      dtype='object')

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3251 entries, 0 to 3250
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   postcode    3251 non-null   int64
 1   suburb      3251 non-null   object
 2   state       3234 non-null   object
 3   city        3251 non-null   object
 4   statecode   3251 non-null   object
 5   1_br_flat   346 non-null    float64
 6   2_br_flat   426 non-null    float64
 7   3_br_flat   363 non-null    float64
 8   4_br_flat   98 non-null     float64
 9   1_br_house  2 non-null      float64
 10  2_br_house  387 non-null    float64
 11  3_br_house  592 non-null    float64
 12  4_br_house  572 non-null    float64
dtypes: float64(8), int64(1), object(4)
memory usage: 330.3+ KB

In [109]:
duplicate = df[df.duplicated()]
print("Duplicate Rows :")
duplicate

Duplicate Rows :

2       True
3       True
4       True
5       True
6       True
        ...
3246    True
3247    True
3248    True
3249    True
3250    True
Length: 3249, dtype: bool

In [102]:
#--- take the means to replace the zero in baths & bed ---
df['1_br_flat'] = df['1_br_flat'].replace([np.nan], df['1_br_flat'].median())
df['2_br_flat'] = df['2_br_flat'].replace([np.nan], df['2_br_flat'].median())
df['3_br_flat'] = df['3_br_flat'].replace([np.nan], df['3_br_flat'].median())
df['4_br_flat'] = df['4_br_flat'].replace([np.nan], df['4_br_flat'].median())
df['1_br_house'] = df['1_br_house'].replace([np.nan], df['1_br_house'].median())
df['2_br_house'] = df['2_br_house'].replace([np.nan], df['2_br_house'].median())
df['3_br_house'] = df['3_br_house'].replace([np.nan], df['3_br_house'].median())
df['4_br_house'] = df['4_br_house'].replace([np.nan], df['4_br_house'].median())
df['state'] = df['state'].replace([np.nan], ['Brisbane'])

In [103]:
df.head()

,postcode,suburb,state,city,statecode,1_br_flat,2_br_flat,3_br_flat,4_br_flat,1_br_house,2_br_house,3_br_house,4_br_house
0,4000,Brisbane,Brisbane,Queensland,QLD,350.0,400.0,500.0,716.666667,250.0,380.0,420.0,530.0
1,4000,Brisbane Adelaide Street,Brisbane,Queensland,QLD,250.0,300.0,390.0,628.166667,250.0,325.0,387.5,460.0
2,4000,Spring Hill,Brisbane,Queensland,QLD,400.0,520.0,758.0,912.666667,250.0,410.0,520.0,510.0
3,4001,Central Plaza,Brisbane,Queensland,QLD,250.0,300.0,390.0,628.166667,250.0,325.0,387.5,460.0
4,4001,Riverside Centre,Brisbane,Queensland,QLD,250.0,300.0,390.0,628.166667,250.0,325.0,387.5,460.0

In [104]:
df.isnull().sum()

postcode      0
suburb        0
state         0
city          0
statecode     0
1_br_flat     0
2_br_flat     0
3_br_flat     0
4_br_flat     0
1_br_house    0
2_br_house    0
3_br_house    0
4_br_house    0
dtype: int64

In [70]:
# Replace NaN with zero on all columns 
df = df.fillna(0)

In [105]:
from google.colab import files
df.to_csv('FinalQld.csv') 
files.download('FinalQld.csv')