<a href="https://colab.research.google.com/github/slng09/advance-task22/blob/main/transportcleanfile.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd
import numpy as np
import pandas as pd
from scipy import stats
from matplotlib import pyplot as plt
import seaborn as sns

#--- suppress warnings ---
import warnings
warnings.filterwarnings("ignore")

In [117]:
# Read CSV
from google.colab import files
uploaded = files.upload()
import io
df = pd.read_csv(io.BytesIO(uploaded["Tasmania - Metro Hobart _GTFS v2.csv"]),sep=',')
df.head()

Saving Tasmania - Metro Hobart _GTFS v2.csv to Tasmania - Metro Hobart _GTFS v2.csv

,stop_id,stop_name,stop_lat,stop_lon,mode,state code
0,434,45 Stratton Ave Stratton Ave near Baldwin Pl,-42.859574,147.277761,train,TA
1,512,** Stop Closed [Acton Cr #37],-42.827829,147.288276,train,TA
2,513,** Stop Closed [Acton Cr #38],-42.826764,147.289645,train,TA
3,3886,** Stop Deleted,-42.734262,147.240605,train,TA
4,4143,** Stop Not In Use,-42.857649,147.401647,train,TA

In [125]:
df.isnull().sum()

stop_id       0
stop_name     0
latitude      0
longtitude    0
mode          0
state_code    0
dtype: int64

In [119]:
def clean_column_name(column_names):
    clean_column_names = []
    for c in column_names:
        c = c.lower().replace(' ','_')
        clean_column_names.append(c)
    return clean_column_names    

df.columns = clean_column_name(df.columns)

In [122]:
df.columns = ['stop_id', 'stop_name', 'latitude', 'longtitude', 'mode', 'state_code'] 
df.columns

Index(['stop_id', 'stop_name', 'latitude', 'longtitude', 'mode', 'state_code'], dtype='object')

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2457 entries, 0 to 2456
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   stop_id     2457 non-null   object
 1   stop_name   2457 non-null   object
 2   latitude    2457 non-null   float64
 3   longtitude  2457 non-null   float64
 4   mode        2457 non-null   object
 5   state_code  2457 non-null   object
dtypes: float64(2), object(4)
memory usage: 115.3+ KB

In [124]:
duplicate = df[df.duplicated()]
print("Duplicate Rows :")
duplicate

Duplicate Rows :

Empty DataFrame
Columns: [stop_id, stop_name, latitude, longtitude, mode, state_code]
Index: []

In [102]:
#--- take the means to replace the zero in baths & bed ---
df['1_br_flat'] = df['1_br_flat'].replace([np.nan], df['1_br_flat'].median())
df['2_br_flat'] = df['2_br_flat'].replace([np.nan], df['2_br_flat'].median())
df['3_br_flat'] = df['3_br_flat'].replace([np.nan], df['3_br_flat'].median())
df['4_br_flat'] = df['4_br_flat'].replace([np.nan], df['4_br_flat'].median())
df['1_br_house'] = df['1_br_house'].replace([np.nan], df['1_br_house'].median())
df['2_br_house'] = df['2_br_house'].replace([np.nan], df['2_br_house'].median())
df['3_br_house'] = df['3_br_house'].replace([np.nan], df['3_br_house'].median())
df['4_br_house'] = df['4_br_house'].replace([np.nan], df['4_br_house'].median())
df['state'] = df['state'].replace([np.nan], ['Brisbane'])

In [103]:
df.head()

,postcode,suburb,state,city,statecode,1_br_flat,2_br_flat,3_br_flat,4_br_flat,1_br_house,2_br_house,3_br_house,4_br_house
0,4000,Brisbane,Brisbane,Queensland,QLD,350.0,400.0,500.0,716.666667,250.0,380.0,420.0,530.0
1,4000,Brisbane Adelaide Street,Brisbane,Queensland,QLD,250.0,300.0,390.0,628.166667,250.0,325.0,387.5,460.0
2,4000,Spring Hill,Brisbane,Queensland,QLD,400.0,520.0,758.0,912.666667,250.0,410.0,520.0,510.0
3,4001,Central Plaza,Brisbane,Queensland,QLD,250.0,300.0,390.0,628.166667,250.0,325.0,387.5,460.0
4,4001,Riverside Centre,Brisbane,Queensland,QLD,250.0,300.0,390.0,628.166667,250.0,325.0,387.5,460.0

In [104]:
df.isnull().sum()

postcode      0
suburb        0
state         0
city          0
statecode     0
1_br_flat     0
2_br_flat     0
3_br_flat     0
4_br_flat     0
1_br_house    0
2_br_house    0
3_br_house    0
4_br_house    0
dtype: int64

In [70]:
# Replace NaN with zero on all columns 
df = df.fillna(0)

In [126]:
from google.colab import files
df.to_csv('Tasmania - Metro Hobart _GTFS v2.csv') 
files.download('Tasmania - Metro Hobart _GTFS v2.csv')